name: infofleet_adm
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  
  # Navegação e Gestão de Estado
  get: ^4.7.3

  # Requisições HTTP (API)
  dio: ^5.8.0

  # Armazenamento Local e Segurança
  flutter_secure_storage: ^9.2.4
  get_storage: ^2.1.1

  # Interface e UX
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

  # Utilitários e Core
  intl: ^0.19.0
  logger: ^2.0.2
  equatable: ^2.0.5
  connectivity_plus: ^6.1.4

  # Serialização de JSON
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Geração de Código para JSON
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  
  # Linting (Boas práticas de código)
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/infofleet_adm_icon.png" # O caminho da tua imagem
  min_sdk_android: 21 # Suporte mínimo da tua app

flutter:
  uses-material-design: true

  assets:
    - assets/images/

        
    
    
                                      